//
// Created by Andri Yadi on 8/25/16.
//

#ifndef XBOARD_ESPECTRO_CONSTANTS_H_H
#define XBOARD_ESPECTRO_CONSTANTS_H_H

//Constants
#define ESPECTRO_LED_PIN 15

#define ESPECTRO_BUTTON_PIN 2
#define ESPECTRO_BUTTON_DEBOUNCE_DURATION_MS      50
#define ESPECTRO_BUTTON_PRESS_DURATION_MS         100
#define ESPECTRO_BUTTON_LONG_PRESS_DURATION_MS    700

#endif //XBOARD_ESPECTRO_CONSTANTS_H_H
